"""empty message

Revision ID: 565b82e69882
Revises: f34ee00d9d42
Create Date: 2020-04-15 01:16:10.806978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565b82e69882'
down_revision = 'f34ee00d9d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=True))
    op.drop_column('user', 'paswword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paswword', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
