"""empty message

Revision ID: 5d9009c82730
Revises: ff1514306d5b
Create Date: 2020-04-11 02:57:38.367713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9009c82730'
down_revision = 'ff1514306d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('paswword', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=30), nullable=True))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['phoneNumber'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 'role')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'paswword')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
