"""empty message

Revision ID: b7e53ce899a5
Revises: 5d9009c82730
Create Date: 2020-04-11 03:01:01.918059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e53ce899a5'
down_revision = '5d9009c82730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
